
FROM python:3.9-slim


WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-tk \
    libx11-dev \
    && rm -rf /var/lib/apt/lists/*



COPY  requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY . /app/.




EXPOSE 65432


CMD ["python", "cliente_main.py"]