
services:
  servidor:
    build: ./server
    ports:
      - "65432:65432"  # Mapeia a porta do servidor para a máquina host
    networks:
      - rede_teste

  cliente:
    build: ./client
    depends_on:
      - servidor  # Garante que o servidor estará disponível antes de iniciar o cliente
    networks:
      - rede_teste
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  rede_teste:
    driver: bridge