# Usando a imagem oficial do Python
FROM python:3.9-slim

# Definir o diretório de trabalho dentro do container
WORKDIR /app



COPY . /app/.


# Expor a porta que o servidor irá utilizar
EXPOSE 65432

# Definir o comando para rodar o servidor
CMD ["python", "main.py"]